FROM ubuntu
RUN apt update
RUN apt install cowsay -y python3 -y && pip install fastapi uvicorn




    # FROM python
    # RUN pip install fastapi uvicorn
    # COPY main.py main.py
    # CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=65534"]

