version: "3"
services:
  my-api:
    build: .
    ports:
      - "8000:8000"

  web:
    image: nginx
    ports: 
      - "80:80"

  db: # docker exec -it -u postgres <container-id> psql
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password 
    ports:
      - "5432:5432"

  cache: # docker exec -it <container-id> redis-cli
    image: redis
    ports:
      - "6379:6379"

  queue:
    image: rabbitmq